enum TipoTexto { TITULO, CABECALHO, CORPO, RODAPE, ACAO, INFERIOR, LOADING, BTNOK, BTNCANCEL,RADIO, PLACEHOLDER, DROPDOWN }
enum DialogState { LOADING, COMPLETED, DISMISSED, ERROR }
enum Modulo { AGENDAMENTO, AVALIACAO, FILAVIRTUAL, DISPONIBILIDADE }