name: gti_sesa_saude
description: Aplicativo da Prefeitura da Serra- ES.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  

dependencies:
  http: ^0.12.0+1
  json_annotation: ^2.0.0
  rxdart: ^0.20.0
  #geocoder: ^0.1.2
  intl: ^0.15.7
  back_button_interceptor: ^2.0.0 
  google_maps_flutter: ^0.5.7 

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:            
    - img/logo_icon.png
    - img/background.png
    - img/cabecalho.png
    - img/pms.png
    - img/gti.png
    - img/coracao.png
    - img/unidade.png
    - img/splash.png
    - img/passo01.jpg
    - img/passo02.jpg
    - img/passo03.jpg
    - img/passo04.jpg
    - img/passo05.jpg
    - img/ic_passo01.png
    - img/ic_passo02.png
    - img/ic_passo03.png
    - img/ic_passo04.png
    - img/ic_passo05.png
    - img/ic_agendamento.png
    - img/ic_fila.png
    - img/ic_avaliacao.png
    - img/ic_bom.png
    - img/ic_otimo.png
    - img/ic_pessimo.png
    - img/ic_regular.png
    - img/ic_ruim.png

    

    
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Humanist
      fonts:
        - asset: fonts/Humanist.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
